const dashboardlIst = {
  new: [
    {
      title: "ABC",
      subtitle: "Abcde Fghi",
      time: "9s",
      address: "Efls...lap2",
      user: "3%",
      socialLink: "twitter.com",
    },
    {
      title: "DEF",
      subtitle: "Defg Hijk",
      time: "15s",
      address: "Efls...lap2",
      user: "4%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "GHI",
      subtitle: "Ghij Klmn",
      time: "22s",
      address: "Efls...lap2",
      user: "6%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "HIJ",
      subtitle: "Hijkl Mnopq",
      time: "34min",
      address: "Efls...lap2",
      user: "9%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "JKL",
      subtitle: "Jklm Nopq",
      time: "2h",
      address: "Efls...lap2",
      user: "15%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "LMNo",
      subtitle: "Lmnop Qrst",
      time: "5h",
      address: "Efls...lap2",
      user: "45%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "PQRS",
      subtitle: "Pqrst Uvwx",
      time: "2d",
      address: "Efls...lap2",
      user: "54%",
      social: "twitter.com",
      buyLink: "#",
    },
  ],
  completing: [
    {
      title: "ABC",
      subtitle: "Abcde Fghi",
      time: "9s",
      address: "Efls...lap2",
      user: "3%",
      socialLink: "twitter.com",
      buyLink: "#",
    },
    {
      title: "DEF",
      subtitle: "Defg Hijk",
      time: "15s",
      address: "Efls...lap2",
      user: "4%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "GHI",
      subtitle: "Ghij Klmn",
      time: "22s",
      address: "Efls...lap2",
      user: "6%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "HIJ",
      subtitle: "Hijkl Mnopq",
      time: "34min",
      address: "Efls...lap2",
      user: "9%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "JKL",
      subtitle: "Jklm Nopq",
      time: "2h",
      address: "Efls...lap2",
      user: "15%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "LMNo",
      subtitle: "Lmnop Qrst",
      time: "5h",
      address: "Efls...lap2",
      user: "45%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "PQRS",
      subtitle: "Pqrst Uvwx",
      time: "2d",
      address: "Efls...lap2",
      user: "54%",
      social: "twitter.com",
      buyLink: "#",
    },
  ],
  completed: [
    {
      title: "ABC",
      subtitle: "Abcde Fghi",
      time: "9s",
      address: "Efls...lap2",
      user: "3%",
      socialLink: "twitter.com",
      buyLink: "#",
    },
    {
      title: "DEF",
      subtitle: "Defg Hijk",
      time: "15s",
      address: "Efls...lap2",
      user: "4%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "GHI",
      subtitle: "Ghij Klmn",
      time: "22s",
      address: "Efls...lap2",
      user: "6%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "HIJ",
      subtitle: "Hijkl Mnopq",
      time: "34min",
      address: "Efls...lap2",
      user: "9%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "JKL",
      subtitle: "Jklm Nopq",
      time: "2h",
      address: "Efls...lap2",
      user: "15%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "LMNo",
      subtitle: "Lmnop Qrst",
      time: "5h",
      address: "Efls...lap2",
      user: "45%",
      social: "twitter.com",
      buyLink: "#",
    },
    {
      title: "PQRS",
      subtitle: "Pqrst Uvwx",
      time: "2d",
      address: "Efls...lap2",
      user: "54%",
      social: "twitter.com",
      buyLink: "#",
    },
  ],
};

import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json(dashboardlIst);
}
